=== didier-mycontrib/tp_xml/exemples/xml_xsd/ex_region_dep/france.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   
<xsd:element name='pays' type='Pays' />    
    
<xsd:complexType name="Pays">
		<xsd:sequence>			
			<xsd:element name="region" type="Region" maxOccurs='20' />			
		</xsd:sequence>
		<xsd:attribute name="nom" type="xsd:string"/>
		<xsd:attribute name="capitale" type="xsd:string"/>
</xsd:complexType>				

<xsd:complexType name="Region">
		<xsd:sequence>			
			<xsd:element name="departement" type="Departement" maxOccurs='8' />			
		</xsd:sequence>
		<xsd:attribute name="nom" type="xsd:string"/>
</xsd:complexType>

<xsd:complexType name="Departement">		
		<xsd:attribute name="nom" type="xsd:string"/>
		<xsd:attribute name="num" type="xsd:positiveInteger"/>
		<xsd:attribute name="prefecture" type="xsd:string"/>
</xsd:complexType>				
				

	
</xsd:schema>

=== didier-mycontrib/tp_xml/exemples/xml_xsd/ex_region_dep/france_explicit_ns.xml
<?xml version='1.0' encoding='UTF-8' standalone='yes' ?>
<!-- commentaire -->
<geo:pays xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
      xmlns:geo="http://www.example.org/geo"
      xsi:schemaLocation="http://www.example.org/geo france.xsd"
      nom='France' capitale='Paris' >
    <geo:region nom='Haute-Normandie' >
    	<geo:departement nom='Eure' num='27' prefecture='Evreux' />
        <geo:departement nom='Seine Maritime' num='76' prefecture='Rouen' />        
    </geo:region>
    <geo:region nom='Picardie'>
         <geo:departement nom='Somme' num='80' prefecture='Amiens' />
         <geo:departement nom='Oise' num='60' prefecture='Beauvais' />
         <geo:departement nom='Aisne' num='02' prefecture='Laon' />
    </geo:region>
</geo:pays>
